receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  gelfudp:
    endpoint: localhost:12201
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, gelfudp]
