dist:
  name: otelcol-custom
  description: Local OpenTelemetry Collector binary
  output_path: ./otelcol-custom
  debug_compilation: true
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.122.0
  - gomod: github.com/tomsobpl/otel-gelf-exporter v0.0.0
    import: github.com/tomsobpl/otel-gelf-exporter/pkg/gelftcpexporter
    path: ./gelfexporter
  - gomod: github.com/tomsobpl/otel-gelf-exporter v0.0.0
    import: github.com/tomsobpl/otel-gelf-exporter/pkg/gelfudpexporter
    path: ./gelfexporter
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.122.0
