receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  gelftcp:
    endpoint: ${env:OTEL_EXPORTER_GELF_TCP_ENDPOINT}
  gelfudp:
    endpoint: ${env:OTEL_EXPORTER_GELF_UDP_ENDPOINT}
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, gelftcp, gelfudp]
