dist:
  name: otelcol-custom
  description: Local OpenTelemetry Collector binary
  output_path: ./otelcol-custom
  debug_compilation: true
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.119.0
  - gomod: github.com/tomsobpl/otel-collector-graylog/exporter/gelftcpexporter main
    path: ./gelftcpexporter
  - gomod: github.com/tomsobpl/otel-collector-graylog/exporter/gelfudpexporter main
    path: ./gelfudpexporter
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.119.0
